// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfX0ZLkPg1FVS0cUqjCWuL7JHRvG-aRHM',
    appId: '1:464549699144:web:350915774c27f78426c27d',
    messagingSenderId: '464549699144',
    projectId: 'attempt1-314eb',
    authDomain: 'attempt1-314eb.firebaseapp.com',
    storageBucket: 'attempt1-314eb.firebasestorage.app',
    measurementId: 'G-E86TFSSD9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYbtvZbFN6ilSjEZTAOFIsV-67GhFBuWM',
    appId: '1:464549699144:android:083fd3947d97162a26c27d',
    messagingSenderId: '464549699144',
    projectId: 'attempt1-314eb',
    storageBucket: 'attempt1-314eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-91BP3HgJb-1qf-piwunOQib3LDjtNNA',
    appId: '1:464549699144:ios:c1b0a15562db54e426c27d',
    messagingSenderId: '464549699144',
    projectId: 'attempt1-314eb',
    storageBucket: 'attempt1-314eb.firebasestorage.app',
    iosBundleId: 'com.example.attempt1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-91BP3HgJb-1qf-piwunOQib3LDjtNNA',
    appId: '1:464549699144:ios:c1b0a15562db54e426c27d',
    messagingSenderId: '464549699144',
    projectId: 'attempt1-314eb',
    storageBucket: 'attempt1-314eb.firebasestorage.app',
    iosBundleId: 'com.example.attempt1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfX0ZLkPg1FVS0cUqjCWuL7JHRvG-aRHM',
    appId: '1:464549699144:web:add21dc3989a60dd26c27d',
    messagingSenderId: '464549699144',
    projectId: 'attempt1-314eb',
    authDomain: 'attempt1-314eb.firebaseapp.com',
    storageBucket: 'attempt1-314eb.firebasestorage.app',
    measurementId: 'G-PJ63RNQRWX',
  );

}